In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
df=pd.read_csv('/home/kaeshav/Documents/Convolve/Dev_data_to_be_shared.csv')

In [5]:
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96806 entries, 0 to 96805
Columns: 1216 entries, account_number to onus_attribute_48
dtypes: float64(1189), int64(27)
memory usage: 898.1 MB


account_number  bad_flag  onus_attribute_1  transaction_attribute_1  \
0               1         0               NaN                      NaN   
1               2         0          221000.0                      0.0   
2               3         0           25000.0                      0.0   
3               4         0           86000.0                      0.0   
4               5         0          215000.0                      0.0   

   transaction_attribute_2  transaction_attribute_3  transaction_attribute_4  \
0                      NaN                      NaN                      NaN   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   transaction_attribute_5  transaction_attribute_6  transaction_attribute_7  \
0                      NaN                      NaN                      NaN   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   ...  bureau_enquiry_47  bureau_enquiry_48  bureau_enquiry_49  \
0  ...                0.0                0.0                0.0   
1  ...                0.0                0.0                2.0   
2  ...                0.0                0.0                0.0   
3  ...                0.0                0.0                0.0   
4  ...                0.0                0.0                0.0   

   bureau_enquiry_50  onus_attribute_43  onus_attribute_44  onus_attribute_45  \
0                1.0                NaN                NaN                NaN   
1                3.0                0.0                0.0                0.0   
2                8.0                NaN                NaN                NaN   
3               30.0                NaN                NaN                NaN   
4                1.0                NaN                NaN                NaN   

   onus_attribute_46  onus_attribute_47  onus_attribute_48  
0                NaN                NaN                NaN  
1                0.0                0.0                0.0  
2                NaN                NaN                NaN  
3                NaN                NaN                NaN  
4                NaN                NaN                NaN  

[5 rows x 1216 columns]

In [6]:
df1 = df.fillna(0)

In [7]:
X=df1.drop(['bad_flag'],axis=1)
X=X.drop(['account_number'],axis=1)
y=df1['bad_flag']

In [8]:
numeric_features=X.select_dtypes(include=['int64','float']).columns
print(numeric_features)

Index(['onus_attribute_1', 'transaction_attribute_1',
       'transaction_attribute_2', 'transaction_attribute_3',
       'transaction_attribute_4', 'transaction_attribute_5',
       'transaction_attribute_6', 'transaction_attribute_7',
       'transaction_attribute_8', 'transaction_attribute_9',
       ...
       'bureau_enquiry_47', 'bureau_enquiry_48', 'bureau_enquiry_49',
       'bureau_enquiry_50', 'onus_attribute_43', 'onus_attribute_44',
       'onus_attribute_45', 'onus_attribute_46', 'onus_attribute_47',
       'onus_attribute_48'],
      dtype='object', length=1214)


In [9]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report, roc_auc_score, log_loss
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler

In [12]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
y=y.values.reshape(-1,1)
y_scaled=scaler.fit_transform(y)

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [14]:
model=LogisticRegressionCV()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print('Accuracy score:', accuracy_score(y_pred,y_test)*100)
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

Accuracy score: 98.45057328788349
[[19062   278]
 [   22     0]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     19340
           1       0.00      0.00      0.00        22

    accuracy                           0.98     19362
   macro avg       0.50      0.49      0.50     19362
weighted avg       1.00      0.98      0.99     19362



In [15]:
model1=XGBClassifier()
model1.fit(X_train,y_train)
y_pred1=model1.predict(X_test)
print('Accuracy score:', accuracy_score(y_pred1,y_test)*100)
print(confusion_matrix(y_pred1,y_test))
print(classification_report(y_pred1,y_test))

Accuracy score: 98.55903315773163
[[19083   278]
 [    1     0]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     19361
           1       0.00      0.00      0.00         1

    accuracy                           0.99     19362
   macro avg       0.50      0.49      0.50     19362
weighted avg       1.00      0.99      0.99     19362



In [17]:
model2=AdaBoostClassifier()
model2.fit(X_train,y_train)
y_pred2=model2.predict(X_test)
print('Accuracy score:', accuracy_score(y_pred2,y_test)*100)
y_prob = model2.predict_proba(X_test)[:, 1]  
# Metrics
#accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
logloss = log_loss(y_test, y_prob)
#f1 = f1_score(y_test, y_pred)

gini = 2 * roc_auc - 1  # Gini coefficient from AUC

print("AUC-ROC:",roc_auc)
print("Log Loss:",logloss)
print("Gini Coefficient:", gini)
print(confusion_matrix(y_pred2,y_test))
print(classification_report(y_pred2,y_test))

Accuracy score: 98.55903315773163
AUC-ROC: 0.8010109414040765
Log Loss: 0.6255704741035657
Gini Coefficient: 0.6020218828081529
[[19081   276]
 [    3     2]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     19357
           1       0.01      0.40      0.01         5

    accuracy                           0.99     19362
   macro avg       0.50      0.69      0.50     19362
weighted avg       1.00      0.99      0.99     19362



In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
model3 = RandomForestClassifier(n_estimators=100, random_state=42)  
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)
print('Accuracy score:', accuracy_score(y_pred3, y_test) * 100)
print(confusion_matrix(y_pred3, y_test))
print(classification_report(y_pred3, y_test))

Accuracy score: 98.56419791343869
[[19084   278]
 [    0     0]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     19362
           1       0.00      0.00      0.00         0

    accuracy                           0.99     19362
   macro avg       0.50      0.49      0.50     19362
weighted avg       1.00      0.99      0.99     19362



# **Validation** #

In [20]:
validation_data = pd.read_csv('/home/kaeshav/Documents/Convolve/validation_data_to_be_shared.csv')


In [21]:
validation_data_filled = validation_data.fillna(0)
validation_data_filled = validation_data_filled.drop(["account_number"],axis=1)

In [22]:
numeric_features=validation_data_filled.select_dtypes(include=['int64','float']).columns
numeric_features

Index(['onus_attribute_1', 'transaction_attribute_1',
       'transaction_attribute_2', 'transaction_attribute_3',
       'transaction_attribute_4', 'transaction_attribute_5',
       'transaction_attribute_6', 'transaction_attribute_7',
       'transaction_attribute_8', 'transaction_attribute_9',
       ...
       'bureau_enquiry_47', 'bureau_enquiry_48', 'bureau_enquiry_49',
       'bureau_enquiry_50', 'onus_attribute_43', 'onus_attribute_44',
       'onus_attribute_45', 'onus_attribute_46', 'onus_attribute_47',
       'onus_attribute_48'],
      dtype='object', length=1214)

In [23]:
X_validation = validation_data_filled[numeric_features]

In [24]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X_validation)

In [25]:
X_validation_scaled = scaler.transform(X_validation)

# **LogisticRegressionCV** #

In [27]:
validation_data['predicted_probability'] = model.predict(X_validation_scaled)  # For the Random Forest
submission = validation_data[['account_number', 'predicted_probability']]
submission.to_csv('submission_LCV.csv', index=False)

print("Prediction for validation data saved to 'submission_LCV.csv'")

Prediction for validation data saved to 'submission_LCV.csv'


# **XGBClassifier

In [29]:
validation_data['predicted_probability'] = model1.predict(X_validation_scaled)  # For the Random Forest
submission = validation_data[['account_number', 'predicted_probability']]
submission.to_csv('submission_XGB.csv', index=False)

print("Prediction for validation data saved to 'submission_XGB.csv'")

Prediction for validation data saved to 'submission_XGB.csv'


# **AdaBoost** #

In [30]:
validation_data['predicted_probability'] = model2.predict(X_validation_scaled)  # For the Random Forest
submission = validation_data[['account_number', 'predicted_probability']]
submission.to_csv('submission_Ada.csv', index=False)

print("Prediction for validation data saved to 'submission_Ada.csv'")

Prediction for validation data saved to 'submission_Ada.csv'


# **Random Forest** #

In [40]:
validation_data['predicted_probability'] = model3.predict(X_validation_scaled)  # For the Random Forest
submission = validation_data[['account_number', 'predicted_probability']]
submission.to_csv('submission_RF.csv', index=False)

print("Prediction for validation data saved to 'submission_RF.csv'")

Prediction for validation data saved to 'submission_RF.csv'


# **Neural Network** #

In [38]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss
import numpy as np


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)  

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=1)

y_train = np.array(y_train)
y_test = np.array(y_test)

# Build the neural network model
model4 = Sequential([
    Dense(128, input_dim=X_train.shape[1], activation='relu'),  # Input layer
    Dropout(0.4), 
    Dense(128, activation='relu'),  # Hidden layer
    Dropout(0.4),
    Dense(1, activation='sigmoid')  # Output layer 

# Compile the model
model4.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model4.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=30, batch_size=64, verbose=1)

# Evaluate the model
y_pred_proba = model4.predict(X_test).flatten()  # Predicted probabilities
y_pred = (y_pred_proba > 0.5).astype(int)  # Convert probabilities to binary predictions

accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)
logloss = log_loss(y_test, y_pred_proba)

print("Accuracy:", accuracy)
print("AUC-ROC:", roc_auc)
print("Log Loss:", logloss)



Epoch 1/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9709 - loss: 0.1144 - val_accuracy: 0.9856 - val_loss: 0.0708
Epoch 2/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.9863 - loss: 0.0709 - val_accuracy: 0.9856 - val_loss: 0.0690
Epoch 3/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.9862 - loss: 0.0671 - val_accuracy: 0.9856 - val_loss: 0.0677
Epoch 4/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 732us/step - accuracy: 0.9854 - loss: 0.0672 - val_accuracy: 0.9856 - val_loss: 0.0688
Epoch 5/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.9855 - loss: 0.0628 - val_accuracy: 0.9856 - val_loss: 0.0666
Epoch 6/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.9860 - loss: 0.0616 - val_accuracy: 0.9856 - val_loss: 0.0677
Epoch 7/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.9855 - loss: 0.0611 - val_accuracy: 0.9856 - val_loss: 0.0714
Epoch 8/30
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 744us/step - accuracy: 0.9858 - l

In [42]:
predicted_probability = model4.predict(X_validation_scaled).flatten()

predicted_class = (predicted_probability > 0.5).astype(int)

validation_data['predicted_class'] = predicted_class

submission = validation_data[['account_number', 'predicted_class']]

submission.to_csv('submission_NN.csv', index=False)
print("Prediction for validation data saved to 'submission_NN.csv'")

1306/1306 ━━━━━━━━━━━━━━━━━━━━ 1s 473us/step
Prediction for validation data saved to 'submission_NN.csv'
